name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install jupyter-book ghp-import
<!--
      - name: Clean previous builds
        run: |
          jupyter-book clean tempBook2 --all || true
          
      - name: List book files
        run: |
          ls -R tempBook2

      - name: Build Jupyter Book
        run: |
          jupyter-book clean tempBook2 --all || true
          jupyter-book build tempBook2 --debug
          ls -R tempBook2/_build/html
-->
      - name: Build Jupyter Book # Change this to new repo name
        run: |
          cd tempBook2  
          jupyter-book build .
          
      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f tempBook2/_build/html
